/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Core NextHire Brand Colors
        "primary": "#004ac6",
        "on-primary": "#ffffff",
        "primary-container": "#2563eb",
        "on-primary-container": "#eeefff",
        "inverse-primary": "#b4c5ff",
        "primary-hover": "#003ea8",
        "primary-active": "#003289",

        // High-Contrast Surfaces
        "surface": "#f7f9fb",
        "surface-dim": "#d8dadc",
        "surface-bright": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f1f5f9",
        "surface-container": "#eceef0",
        "surface-container-high": "#e2e8f0",
        "surface-container-highest": "#cbd5e1",
        "on-surface": "#0f172a",
        "on-surface-variant": "#334155",
        "inverse-surface": "#1e293b",
        "inverse-on-surface": "#f8fafc",
        "outline": "#64748b",
        "outline-variant": "#cbd5e1",
        "surface-tint": "#0053db",
        "background": "#f7f9fb",
        "on-background": "#0f172a",
        "surface-variant": "#e2e8f0",

        // Standardized Neutral Scale
        neutral: {
          50: "#f8fafc",
          100: "#f1f5f9",
          200: "#e2e8f0",
          300: "#cbd5e1",
          400: "#94a3b8",
          500: "#64748b",
          600: "#475569",
          700: "#334155",
          800: "#1e293b",
          900: "#0f172a",
          950: "#020617",
        },

        // Semantic Palette (Success, Warning, Error, Info)
        "success": {
          DEFAULT: "#166534",
          bg: "#dcfce7",
          border: "#86efac",
          text: "#14532d",
        },
        "warning": {
          DEFAULT: "#b45309",
          bg: "#fef3c7",
          border: "#fde68a",
          text: "#78350f",
        },
        "error": {
          DEFAULT: "#ba1a1a",
          bg: "#fee2e2",
          border: "#fca5a5",
          text: "#7f1d1d",
        },
        "info": {
          DEFAULT: "#004ac6",
          bg: "#dbeafe",
          border: "#bfdbfe",
          text: "#1e3a8a",
        },

        // AI Match Score Semantic System
        "match-low": {
          DEFAULT: "#dc2626",
          bg: "#fee2e2",
          border: "#fca5a5",
          text: "#991b1b",
        },
        "match-medium": {
          DEFAULT: "#d97706",
          bg: "#fef3c7",
          border: "#fde68a",
          text: "#92400e",
        },
        "match-high": {
          DEFAULT: "#0284c7",
          bg: "#e0f2fe",
          border: "#bae6fd",
          text: "#075985",
        },
        "match-excellent": {
          DEFAULT: "#059669",
          bg: "#d1fae5",
          border: "#a7f3d0",
          text: "#065f46",
        },

        // Secondary & Tertiary
        "secondary": "#475569",
        "on-secondary": "#ffffff",
        "secondary-container": "#dae2fd",
        "on-secondary-container": "#334155",
        "tertiary": "#006242",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#007d55",
        "on-tertiary-container": "#bdffdb",
        "error-container": "#fee2e2",
        "on-error-container": "#991b1b",
        "primary-fixed": "#dbe1ff",
        "primary-fixed-dim": "#b4c5ff",
        "on-primary-fixed": "#00174b",
        "on-primary-fixed-variant": "#003ea8",
        "secondary-fixed": "#dae2fd",
        "secondary-fixed-dim": "#bec6e0",
        "on-secondary-fixed": "#131b2e",
        "on-secondary-fixed-variant": "#3f465c",
        "tertiary-fixed": "#d1fae5",
        "tertiary-fixed-dim": "#a7f3d0",
        "on-tertiary-fixed": "#065f46",
        "on-tertiary-fixed-variant": "#047857",
      },
      borderRadius: {
        "sm": "0.25rem",
        "DEFAULT": "0.5rem",
        "md": "0.75rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "2xl": "1.25rem",
        "3xl": "1.5rem",
        "full": "9999px",
      },
      spacing: {
        "unit": "8px",
        "container-max": "1400px",
        "gutter": "24px",
        "margin-desktop": "40px",
        "margin-mobile": "16px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "32px",
      },
      fontFamily: {
        "display": ["var(--font-poppins)", "sans-serif"],
        "headline-lg": ["var(--font-poppins)", "sans-serif"],
        "headline-md": ["var(--font-poppins)", "sans-serif"],
        "headline-sm": ["var(--font-poppins)", "sans-serif"],
        "body-lg": ["var(--font-hanken)", "sans-serif"],
        "body-md": ["var(--font-hanken)", "sans-serif"],
        "body-sm": ["var(--font-hanken)", "sans-serif"],
        "label-lg": ["var(--font-hanken)", "sans-serif"],
        "label-md": ["var(--font-hanken)", "sans-serif"],
        "label-sm": ["var(--font-hanken)", "sans-serif"],
      },
      boxShadow: {
        "xs": "0 1px 2px 0 rgb(0 0 0 / 0.05)",
        "card": "0 1px 3px 0 rgb(0 0 0 / 0.08), 0 1px 2px -1px rgb(0 0 0 / 0.08)",
        "card-hover": "0 10px 15px -3px rgb(0 0 0 / 0.08), 0 4px 6px -4px rgb(0 0 0 / 0.08)",
      },
    },
  },
  plugins: [],
};
