import { AppEventType, EventMetadataDefinition } from "./types";

export const EVENT_REGISTRY: Record<AppEventType, EventMetadataDefinition> = {
  // --- JOB SEEKER: ACCOUNT & SECURITY ---
  SEEKER_ACCOUNT_CREATED: {
    category: "SECURITY",
    priority: "CRITICAL",
    defaultTitle: "Welcome to NextHire",
    defaultBody: "Your NextHire candidate account has been created successfully.",
    defaultCtaText: "Complete Your Profile",
    defaultCtaUrl: "/profile",
    isMandatory: true,
    emailEligible: true,
    dedupCooldownMinutes: 1440,
  },
  SEEKER_WELCOME: {
    category: "SYSTEM",
    priority: "IMPORTANT",
    defaultTitle: "Get Started on NextHire",
    defaultBody: "Discover verified jobs, upload your resume to AI Resume Studio, and get noticed by top employers.",
    defaultCtaText: "Explore Jobs",
    defaultCtaUrl: "/jobs",
    isMandatory: false,
    emailEligible: true,
    dedupCooldownMinutes: 1440,
  },
  SEEKER_EMAIL_VERIFICATION_SENT: {
    category: "SECURITY",
    priority: "CRITICAL",
    defaultTitle: "Verify Your Email Address",
    defaultBody: "Please verify your email address to unlock full candidate discoverability.",
    defaultCtaText: "Verify Email",
    defaultCtaUrl: "/verify-email",
    isMandatory: true,
    emailEligible: true,
    dedupCooldownMinutes: 15,
  },
  SEEKER_VERIFICATION_COMPLETED: {
    category: "SECURITY",
    priority: "IMPORTANT",
    defaultTitle: "Candidate Profile Verified",
    defaultBody: "Your NextHire candidate account has been verified. You are now discoverable by recruiters.",
    defaultCtaText: "View Profile",
    defaultCtaUrl: "/profile",
    isMandatory: true,
    emailEligible: true,
    dedupCooldownMinutes: 60,
  },
  SEEKER_PASSWORD_CHANGED: {
    category: "SECURITY",
    priority: "CRITICAL",
    defaultTitle: "Security Alert: Password Changed",
    defaultBody: "Your account password was recently updated. If you did not make this change, secure your account immediately.",
    defaultCtaText: "Review Account Security",
    defaultCtaUrl: "/settings",
    isMandatory: true,
    emailEligible: true,
    dedupCooldownMinutes: 0,
  },
  SEEKER_PASSWORD_RESET_REQUESTED: {
    category: "SECURITY",
    priority: "CRITICAL",
    defaultTitle: "Password Reset Request",
    defaultBody: "A request was received to reset your NextHire account password.",
    defaultCtaText: "Reset Password",
    defaultCtaUrl: "/forgot-password",
    isMandatory: true,
    emailEligible: true,
    dedupCooldownMinutes: 5,
  },
  SEEKER_SUSPICIOUS_LOGIN: {
    category: "SECURITY",
    priority: "CRITICAL",
    defaultTitle: "Security Alert: New Sign-in Detected",
    defaultBody: "A new login was detected on your account from an unrecognized device or IP.",
    defaultCtaText: "Check Security",
    defaultCtaUrl: "/settings",
    isMandatory: true,
    emailEligible: true,
    dedupCooldownMinutes: 60,
  },
  SEEKER_ACCOUNT_RESTRICTED: {
    category: "SECURITY",
    priority: "CRITICAL",
    defaultTitle: "Important Account Notice",
    defaultBody: "Your account has been restricted due to a security or policy review.",
    defaultCtaText: "Contact Support",
    defaultCtaUrl: "/help",
    isMandatory: true,
    emailEligible: true,
    dedupCooldownMinutes: 0,
  },
  SEEKER_ACCOUNT_RESTORED: {
    category: "SECURITY",
    priority: "CRITICAL",
    defaultTitle: "Account Access Restored",
    defaultBody: "Your NextHire account access has been fully restored.",
    defaultCtaText: "Go to Dashboard",
    defaultCtaUrl: "/dashboard",
    isMandatory: true,
    emailEligible: true,
    dedupCooldownMinutes: 0,
  },

  // --- JOB SEEKER: PROFILE & ATS RESUME ---
  SEEKER_PROFILE_INCOMPLETE_REMINDER: {
    category: "SYSTEM",
    priority: "INFORMATIONAL",
    defaultTitle: "Boost Your Recruiter Visibility",
    defaultBody: "Your profile is partially complete. Add your key skills and experience to rank higher in searches.",
    defaultCtaText: "Update Profile",
    defaultCtaUrl: "/profile",
    isMandatory: false,
    emailEligible: true,
    dedupCooldownMinutes: 4320, // 3 days
  },
  SEEKER_PROFILE_COMPLETED: {
    category: "SYSTEM",
    priority: "NORMAL",
    defaultTitle: "Profile 100% Complete!",
    defaultBody: "Great job! Your profile is fully optimized for AI matching and recruiter searches.",
    defaultCtaText: "View Profile",
    defaultCtaUrl: "/profile",
    isMandatory: false,
    emailEligible: false,
    dedupCooldownMinutes: 1440,
  },
  SEEKER_PROFILE_VIEWED: {
    category: "JOBS",
    priority: "NORMAL",
    defaultTitle: "A Recruiter Viewed Your Profile",
    defaultBody: "An employer reviewed your candidate profile on NextHire.",
    defaultCtaText: "View Recommendations",
    defaultCtaUrl: "/dashboard",
    isMandatory: false,
    emailEligible: false,
    dedupCooldownMinutes: 720,
  },
  SEEKER_RECRUITER_SAVED_PROFILE: {
    category: "JOBS",
    priority: "IMPORTANT",
    defaultTitle: "You Were Saved to a Talent Pool",
    defaultBody: "A verified recruiter saved your profile for upcoming technical roles.",
    defaultCtaText: "Check Opportunities",
    defaultCtaUrl: "/jobs",
    isMandatory: false,
    emailEligible: true,
    dedupCooldownMinutes: 1440,
  },
  SEEKER_RESUME_UPLOADED: {
    category: "SYSTEM",
    priority: "NORMAL",
    defaultTitle: "Resume Uploaded Successfully",
    defaultBody: "Your PDF resume document has been securely stored.",
    defaultCtaText: "Open Resume Studio",
    defaultCtaUrl: "/resume-studio",
    isMandatory: false,
    emailEligible: false,
    dedupCooldownMinutes: 10,
  },
  SEEKER_RESUME_PARSED: {
    category: "SYSTEM",
    priority: "NORMAL",
    defaultTitle: "Resume Parsed & Intelligence Extracted",
    defaultBody: "Your skills, work history, and education were extracted into your profile.",
    defaultCtaText: "Review Profile",
    defaultCtaUrl: "/profile",
    isMandatory: false,
    emailEligible: false,
    dedupCooldownMinutes: 10,
  },
  SEEKER_RESUME_PARSE_FAILED: {
    category: "SYSTEM",
    priority: "IMPORTANT",
    defaultTitle: "Resume Parsing Notice",
    defaultBody: "We encountered an issue extracting structured text from your resume file. Please verify it is a valid PDF.",
    defaultCtaText: "Re-upload Resume",
    defaultCtaUrl: "/resume-studio",
    isMandatory: false,
    emailEligible: true,
    dedupCooldownMinutes: 60,
  },
  SEEKER_PROFILE_SYNCED: {
    category: "SYSTEM",
    priority: "INFORMATIONAL",
    defaultTitle: "Profile Synchronized",
    defaultBody: "Your Resume Studio changes have been synchronized with your live Candidate Profile.",
    defaultCtaText: "View Profile",
    defaultCtaUrl: "/profile",
    isMandatory: false,
    emailEligible: false,
    dedupCooldownMinutes: 10,
  },
  SEEKER_ATS_SCORE_GENERATED: {
    category: "SYSTEM",
    priority: "NORMAL",
    defaultTitle: "ATS Compatibility Score Generated",
    defaultBody: "Your resume scored for industry standard ATS formatting and keyword density.",
    defaultCtaText: "View ATS Score",
    defaultCtaUrl: "/resume-studio",
    isMandatory: false,
    emailEligible: false,
    dedupCooldownMinutes: 60,
  },
  SEEKER_ATS_SCORE_IMPROVED: {
    category: "SYSTEM",
    priority: "NORMAL",
    defaultTitle: "ATS Score Improved!",
    defaultBody: "Your latest updates improved your ATS resume score.",
    defaultCtaText: "Open Resume Studio",
    defaultCtaUrl: "/resume-studio",
    isMandatory: false,
    emailEligible: false,
    dedupCooldownMinutes: 60,
  },
  SEEKER_PROFILE_IMPROVEMENT_TIP: {
    category: "SYSTEM",
    priority: "INFORMATIONAL",
    defaultTitle: "Profile Optimization Suggestion",
    defaultBody: "Adding verified certifications or GitHub project links can increase your interview rate.",
    defaultCtaText: "Enhance Profile",
    defaultCtaUrl: "/profile",
    isMandatory: false,
    emailEligible: false,
    dedupCooldownMinutes: 4320,
  },

  // --- JOB SEEKER: JOB DISCOVERY ---
  SEEKER_JOB_MATCH_DISCOVERED: {
    category: "JOBS",
    priority: "NORMAL",
    defaultTitle: "New Job Match Found",
    defaultBody: "A newly posted position matches your skills and role preferences.",
    defaultCtaText: "View Job",
    defaultCtaUrl: "/jobs",
    isMandatory: false,
    emailEligible: true,
    dedupCooldownMinutes: 720,
  },
  SEEKER_HIGH_SKILL_MATCH: {
    category: "JOBS",
    priority: "IMPORTANT",
    defaultTitle: "🔥 90%+ Skill Match Opportunity",
    defaultBody: "A new opening directly matches your core technical skillset.",
    defaultCtaText: "Apply Now",
    defaultCtaUrl: "/jobs",
    isMandatory: false,
    emailEligible: true,
    dedupCooldownMinutes: 720,
  },
  SEEKER_SAVED_JOB_CLOSING_SOON: {
    category: "JOBS",
    priority: "IMPORTANT",
    defaultTitle: "Saved Job Closing Soon",
    defaultBody: "A job in your saved list is closing for applications shortly.",
    defaultCtaText: "Submit Application",
    defaultCtaUrl: "/applications",
    isMandatory: false,
    emailEligible: true,
    dedupCooldownMinutes: 1440,
  },
  SEEKER_SAVED_JOB_EXPIRED: {
    category: "JOBS",
    priority: "INFORMATIONAL",
    defaultTitle: "Saved Job Closed",
    defaultBody: "A position in your saved list has been closed or filled.",
    defaultCtaText: "Browse Other Openings",
    defaultCtaUrl: "/jobs",
    isMandatory: false,
    emailEligible: false,
    dedupCooldownMinutes: 1440,
  },
  SEEKER_RECOMMENDED_OPPORTUNITY: {
    category: "JOBS",
    priority: "NORMAL",
    defaultTitle: "Recommended Opportunity",
    defaultBody: "Based on your recent activity, here is a curated job recommendation.",
    defaultCtaText: "Review Job",
    defaultCtaUrl: "/jobs",
    isMandatory: false,
    emailEligible: true,
    dedupCooldownMinutes: 1440,
  },

  // --- JOB SEEKER: APPLICATIONS & MILESTONES ---
  SEEKER_APPLICATION_SUBMITTED: {
    category: "APPLICATIONS",
    priority: "IMPORTANT",
    defaultTitle: "Application Submitted Successfully",
    defaultBody: "Your application was received by the employer and placed in their candidate pipeline.",
    defaultCtaText: "Track Application",
    defaultCtaUrl: "/applications",
    isMandatory: false,
    emailEligible: true,
    dedupCooldownMinutes: 0,
  },
  SEEKER_APPLICATION_RECEIVED: {
    category: "APPLICATIONS",
    priority: "NORMAL",
    defaultTitle: "Application Acknowledged",
    defaultBody: "The hiring team acknowledged receipt of your application.",
    defaultCtaText: "View Status",
    defaultCtaUrl: "/applications",
    isMandatory: false,
    emailEligible: false,
    dedupCooldownMinutes: 0,
  },
  SEEKER_APPLICATION_VIEWED: {
    category: "APPLICATIONS",
    priority: "NORMAL",
    defaultTitle: "Application Reviewed by Recruiter",
    defaultBody: "A recruiter opened and reviewed your application and resume.",
    defaultCtaText: "View Application",
    defaultCtaUrl: "/applications",
    isMandatory: false,
    emailEligible: false,
    dedupCooldownMinutes: 720,
  },
  SEEKER_APPLICATION_SHORTLISTED: {
    category: "APPLICATIONS",
    priority: "IMPORTANT",
    defaultTitle: "🎉 You've Been Shortlisted!",
    defaultBody: "Your application was shortlisted by the hiring team.",
    defaultCtaText: "View Application",
    defaultCtaUrl: "/applications",
    isMandatory: false,
    emailEligible: true,
    dedupCooldownMinutes: 0,
  },
  SEEKER_APPLICATION_STAGE_CHANGED: {
    category: "APPLICATIONS",
    priority: "IMPORTANT",
    defaultTitle: "Application Status Updated",
    defaultBody: "Your application pipeline stage has been updated by the employer.",
    defaultCtaText: "View Progress",
    defaultCtaUrl: "/applications",
    isMandatory: false,
    emailEligible: true,
    dedupCooldownMinutes: 0,
  },
  SEEKER_APPLICATION_REJECTED: {
    category: "APPLICATIONS",
    priority: "IMPORTANT",
    defaultTitle: "Application Update",
    defaultBody: "The hiring team has updated your application status. Recruiter feedback is available.",
    defaultCtaText: "View Feedback",
    defaultCtaUrl: "/applications",
    isMandatory: false,
    emailEligible: true,
    dedupCooldownMinutes: 0,
  },
  SEEKER_APPLICATION_WITHDRAWN: {
    category: "APPLICATIONS",
    priority: "NORMAL",
    defaultTitle: "Application Withdrawn",
    defaultBody: "You have withdrawn your application.",
    defaultCtaText: "View Applications",
    defaultCtaUrl: "/applications",
    isMandatory: false,
    emailEligible: false,
    dedupCooldownMinutes: 0,
  },
  SEEKER_APPLICATION_MILESTONE_REACHED: {
    category: "APPLICATIONS",
    priority: "NORMAL",
    defaultTitle: "Application Milestone Reached!",
    defaultBody: "You have submitted milestone applications on NextHire. Keep up the momentum!",
    defaultCtaText: "View Applications",
    defaultCtaUrl: "/applications",
    isMandatory: false,
    emailEligible: false,
    dedupCooldownMinutes: 1440,
  },

  // --- JOB SEEKER: MESSAGES & INTERVIEWS ---
  SEEKER_MESSAGE_RECEIVED: {
    category: "MESSAGES",
    priority: "IMPORTANT",
    defaultTitle: "New Message from Recruiter",
    defaultBody: "You have received a new recruiter message on NextHire.",
    defaultCtaText: "Reply in Chat",
    defaultCtaUrl: "/messages",
    isMandatory: false,
    emailEligible: true,
    dedupCooldownMinutes: 5,
  },
  SEEKER_RECRUITER_INQUIRY: {
    category: "MESSAGES",
    priority: "IMPORTANT",
    defaultTitle: "Recruiter Direct Inquiry",
    defaultBody: "An employer is interested in your background and sent an inquiry.",
    defaultCtaText: "Open Messages",
    defaultCtaUrl: "/messages",
    isMandatory: false,
    emailEligible: true,
    dedupCooldownMinutes: 30,
  },
  SEEKER_UNANSWERED_MESSAGE_REMINDER: {
    category: "MESSAGES",
    priority: "NORMAL",
    defaultTitle: "Unread Message Reminder",
    defaultBody: "You have an unanswered recruiter message waiting in your inbox.",
    defaultCtaText: "Read Message",
    defaultCtaUrl: "/messages",
    isMandatory: false,
    emailEligible: true,
    dedupCooldownMinutes: 1440,
  },
  SEEKER_INTERVIEW_INVITATION: {
    category: "INTERVIEWS",
    priority: "CRITICAL",
    defaultTitle: "📅 Interview Invitation Received",
    defaultBody: "An employer has invited you to schedule an interview round.",
    defaultCtaText: "Schedule Interview",
    defaultCtaUrl: "/applications",
    isMandatory: false,
    emailEligible: true,
    dedupCooldownMinutes: 0,
  },
  SEEKER_INTERVIEW_SCHEDULED: {
    category: "INTERVIEWS",
    priority: "CRITICAL",
    defaultTitle: "Interview Confirmed & Scheduled",
    defaultBody: "Your interview round is confirmed. View date, time, and meeting link details.",
    defaultCtaText: "View Interview Details",
    defaultCtaUrl: "/applications",
    isMandatory: false,
    emailEligible: true,
    dedupCooldownMinutes: 0,
  },
  SEEKER_INTERVIEW_CONFIRMED: {
    category: "INTERVIEWS",
    priority: "IMPORTANT",
    defaultTitle: "Interview Details Confirmed",
    defaultBody: "The interview panel has confirmed your upcoming session.",
    defaultCtaText: "View Details",
    defaultCtaUrl: "/applications",
    isMandatory: false,
    emailEligible: true,
    dedupCooldownMinutes: 0,
  },
  SEEKER_INTERVIEW_RESCHEDULED: {
    category: "INTERVIEWS",
    priority: "CRITICAL",
    defaultTitle: "Interview Rescheduled",
    defaultBody: "Your interview session date or time has been updated.",
    defaultCtaText: "Review New Time",
    defaultCtaUrl: "/applications",
    isMandatory: false,
    emailEligible: true,
    dedupCooldownMinutes: 0,
  },
  SEEKER_INTERVIEW_REMINDER_24H: {
    category: "INTERVIEWS",
    priority: "IMPORTANT",
    defaultTitle: "Reminder: Interview Tomorrow",
    defaultBody: "You have an interview scheduled for tomorrow. Review the agenda and preparation tips.",
    defaultCtaText: "Interview Room",
    defaultCtaUrl: "/applications",
    isMandatory: false,
    emailEligible: true,
    dedupCooldownMinutes: 720,
  },
  SEEKER_INTERVIEW_REMINDER_1H: {
    category: "INTERVIEWS",
    priority: "CRITICAL",
    defaultTitle: "Starting in 1 Hour: NextHire Interview",
    defaultBody: "Your scheduled interview is starting soon. Ensure your audio and camera are ready.",
    defaultCtaText: "Join Interview",
    defaultCtaUrl: "/applications",
    isMandatory: false,
    emailEligible: true,
    dedupCooldownMinutes: 30,
  },
  SEEKER_INTERVIEW_COMPLETED: {
    category: "INTERVIEWS",
    priority: "NORMAL",
    defaultTitle: "Interview Completed",
    defaultBody: "Thank you for completing your interview session. Status updates will follow.",
    defaultCtaText: "View Application",
    defaultCtaUrl: "/applications",
    isMandatory: false,
    emailEligible: false,
    dedupCooldownMinutes: 0,
  },
  SEEKER_INTERVIEW_FEEDBACK_REQUESTED: {
    category: "INTERVIEWS",
    priority: "INFORMATIONAL",
    defaultTitle: "How Was Your Interview Experience?",
    defaultBody: "Please take a moment to share confidential feedback on your interview process.",
    defaultCtaText: "Give Feedback",
    defaultCtaUrl: "/applications",
    isMandatory: false,
    emailEligible: true,
    dedupCooldownMinutes: 1440,
  },

  // --- JOB SEEKER: OFFERS ---
  SEEKER_OFFER_RECEIVED: {
    category: "APPLICATIONS",
    priority: "CRITICAL",
    defaultTitle: "🎉 Formal Job Offer Extended!",
    defaultBody: "Congratulations! An employer has extended a formal job offer to you.",
    defaultCtaText: "Review Offer",
    defaultCtaUrl: "/applications",
    isMandatory: true,
    emailEligible: true,
    dedupCooldownMinutes: 0,
  },
  SEEKER_OFFER_UPDATED: {
    category: "APPLICATIONS",
    priority: "CRITICAL",
    defaultTitle: "Job Offer Terms Updated",
    defaultBody: "The terms of your formal job offer have been revised by the employer.",
    defaultCtaText: "Review Updated Offer",
    defaultCtaUrl: "/applications",
    isMandatory: true,
    emailEligible: true,
    dedupCooldownMinutes: 0,
  },
  SEEKER_OFFER_DEADLINE_APPROACHING: {
    category: "APPLICATIONS",
    priority: "CRITICAL",
    defaultTitle: "⏰ Offer Decision Deadline Approaching",
    defaultBody: "Your pending job offer requires your formal decision soon.",
    defaultCtaText: "Respond to Offer",
    defaultCtaUrl: "/applications",
    isMandatory: true,
    emailEligible: true,
    dedupCooldownMinutes: 720,
  },
  SEEKER_OFFER_ACCEPTED: {
    category: "APPLICATIONS",
    priority: "IMPORTANT",
    defaultTitle: "Offer Acceptance Confirmed",
    defaultBody: "You have formally accepted the offer. The hiring team has been notified.",
    defaultCtaText: "View Next Steps",
    defaultCtaUrl: "/applications",
    isMandatory: false,
    emailEligible: true,
    dedupCooldownMinutes: 0,
  },
  SEEKER_OFFER_DECLINED: {
    category: "APPLICATIONS",
    priority: "NORMAL",
    defaultTitle: "Offer Declined",
    defaultBody: "You have declined the job offer.",
    defaultCtaText: "View Applications",
    defaultCtaUrl: "/applications",
    isMandatory: false,
    emailEligible: false,
    dedupCooldownMinutes: 0,
  },

  // --- RECRUITER: ACCOUNT & VERIFICATION ---
  RECRUITER_REGISTERED: {
    category: "SECURITY",
    priority: "CRITICAL",
    defaultTitle: "Recruiter Account Created",
    defaultBody: "Welcome to NextHire Recruiter Workspace. Please set up your company profile.",
    defaultCtaText: "Set Up Company",
    defaultCtaUrl: "/recruiter/company",
    isMandatory: true,
    emailEligible: true,
    dedupCooldownMinutes: 1440,
  },
  RECRUITER_WELCOME: {
    category: "SYSTEM",
    priority: "IMPORTANT",
    defaultTitle: "Start Sourcing with NextHire",
    defaultBody: "Access verified technical candidates, post open jobs, and leverage Talent Intelligence.",
    defaultCtaText: "Open Dashboard",
    defaultCtaUrl: "/recruiter",
    isMandatory: false,
    emailEligible: true,
    dedupCooldownMinutes: 1440,
  },
  RECRUITER_VERIFICATION_REQUESTED: {
    category: "SECURITY",
    priority: "IMPORTANT",
    defaultTitle: "Verification Under Review",
    defaultBody: "Your recruiter credentials are under review by NextHire governance.",
    defaultCtaText: "Check Status",
    defaultCtaUrl: "/recruiter",
    isMandatory: false,
    emailEligible: false,
    dedupCooldownMinutes: 60,
  },
  RECRUITER_VERIFICATION_APPROVED: {
    category: "SECURITY",
    priority: "CRITICAL",
    defaultTitle: "Recruiter Verification Approved!",
    defaultBody: "Your recruiter credentials have been approved. You have full candidate sourcing privileges.",
    defaultCtaText: "Search Candidates",
    defaultCtaUrl: "/recruiter/candidates",
    isMandatory: true,
    emailEligible: true,
    dedupCooldownMinutes: 0,
  },
  RECRUITER_VERIFICATION_REJECTED: {
    category: "SECURITY",
    priority: "CRITICAL",
    defaultTitle: "Recruiter Verification Notice",
    defaultBody: "Your recruiter verification could not be approved at this time.",
    defaultCtaText: "Review Account",
    defaultCtaUrl: "/recruiter/profile",
    isMandatory: true,
    emailEligible: true,
    dedupCooldownMinutes: 0,
  },
  RECRUITER_SECURITY_ALERT: {
    category: "SECURITY",
    priority: "CRITICAL",
    defaultTitle: "Security Alert: Recruiter Workspace",
    defaultBody: "A security action or unexpected sign-in was detected on your recruiter profile.",
    defaultCtaText: "Review Security",
    defaultCtaUrl: "/settings",
    isMandatory: true,
    emailEligible: true,
    dedupCooldownMinutes: 60,
  },

  // --- RECRUITER: COMPANY & BRANDING ---
  RECRUITER_COMPANY_CREATED: {
    category: "SYSTEM",
    priority: "NORMAL",
    defaultTitle: "Company Profile Created",
    defaultBody: "Your employer organization profile is now active on NextHire.",
    defaultCtaText: "View Company Profile",
    defaultCtaUrl: "/recruiter/company",
    isMandatory: false,
    emailEligible: false,
    dedupCooldownMinutes: 0,
  },
  RECRUITER_COMPANY_UPDATED: {
    category: "SYSTEM",
    priority: "INFORMATIONAL",
    defaultTitle: "Company Profile Updated",
    defaultBody: "Changes to your company branding, description, or perks have been saved.",
    defaultCtaText: "View Company",
    defaultCtaUrl: "/recruiter/company",
    isMandatory: false,
    emailEligible: false,
    dedupCooldownMinutes: 10,
  },
  RECRUITER_COMPANY_VERIFICATION_SUBMITTED: {
    category: "SECURITY",
    priority: "IMPORTANT",
    defaultTitle: "Company Verification Submitted",
    defaultBody: "Your organization has been submitted for verified employer status.",
    defaultCtaText: "View Status",
    defaultCtaUrl: "/recruiter/company",
    isMandatory: false,
    emailEligible: false,
    dedupCooldownMinutes: 60,
  },
  RECRUITER_COMPANY_VERIFIED: {
    category: "SECURITY",
    priority: "CRITICAL",
    defaultTitle: "Company Verified by NextHire",
    defaultBody: "Your employer organization has received the official Verified Badge.",
    defaultCtaText: "Go to Portal",
    defaultCtaUrl: "/recruiter",
    isMandatory: true,
    emailEligible: true,
    dedupCooldownMinutes: 0,
  },
  RECRUITER_COMPANY_VERIFICATION_REJECTED: {
    category: "SECURITY",
    priority: "CRITICAL",
    defaultTitle: "Company Verification Status",
    defaultBody: "Company verification review was not approved. Please check details.",
    defaultCtaText: "Edit Company",
    defaultCtaUrl: "/recruiter/company",
    isMandatory: true,
    emailEligible: true,
    dedupCooldownMinutes: 0,
  },

  // --- RECRUITER: JOB LIFECYCLE ---
  RECRUITER_JOB_DRAFT_SAVED: {
    category: "JOBS",
    priority: "INFORMATIONAL",
    defaultTitle: "Job Draft Saved",
    defaultBody: "Your job draft has been saved.",
    defaultCtaText: "Edit Job",
    defaultCtaUrl: "/recruiter",
    isMandatory: false,
    emailEligible: false,
    dedupCooldownMinutes: 5,
  },
  RECRUITER_JOB_PUBLISHED: {
    category: "JOBS",
    priority: "IMPORTANT",
    defaultTitle: "Job Published Successfully",
    defaultBody: "Your job opening is now active and published to candidates.",
    defaultCtaText: "View Job",
    defaultCtaUrl: "/recruiter",
    isMandatory: false,
    emailEligible: true,
    dedupCooldownMinutes: 0,
  },
  RECRUITER_JOB_PAUSED: {
    category: "JOBS",
    priority: "NORMAL",
    defaultTitle: "Job Hiring Paused",
    defaultBody: "Applications for this position have been paused.",
    defaultCtaText: "Manage Jobs",
    defaultCtaUrl: "/recruiter",
    isMandatory: false,
    emailEligible: false,
    dedupCooldownMinutes: 0,
  },
  RECRUITER_JOB_RESUMED: {
    category: "JOBS",
    priority: "NORMAL",
    defaultTitle: "Job Hiring Resumed",
    defaultBody: "Position is once again accepting candidate applications.",
    defaultCtaText: "View Job",
    defaultCtaUrl: "/recruiter",
    isMandatory: false,
    emailEligible: false,
    dedupCooldownMinutes: 0,
  },
  RECRUITER_JOB_EXPIRING: {
    category: "JOBS",
    priority: "IMPORTANT",
    defaultTitle: "Job Opening Expiring Soon",
    defaultBody: "Your job posting is nearing its active duration limit.",
    defaultCtaText: "Extend Job Posting",
    defaultCtaUrl: "/recruiter",
    isMandatory: false,
    emailEligible: true,
    dedupCooldownMinutes: 1440,
  },
  RECRUITER_JOB_EXPIRED: {
    category: "JOBS",
    priority: "NORMAL",
    defaultTitle: "Job Posting Expired",
    defaultBody: "The active window for this opening has ended.",
    defaultCtaText: "Reopen Job",
    defaultCtaUrl: "/recruiter",
    isMandatory: false,
    emailEligible: false,
    dedupCooldownMinutes: 0,
  },
  RECRUITER_JOB_APPLICATION_MILESTONE: {
    category: "APPLICATIONS",
    priority: "IMPORTANT",
    defaultTitle: "Application Milestone Reached",
    defaultBody: "Your job opening has reached a key applicant milestone.",
    defaultCtaText: "Review Applicants",
    defaultCtaUrl: "/recruiter/applicants",
    isMandatory: false,
    emailEligible: true,
    dedupCooldownMinutes: 720,
  },

  // --- RECRUITER: CANDIDATE ACTIVITY & ATS ---
  RECRUITER_NEW_APPLICATION: {
    category: "APPLICATIONS",
    priority: "IMPORTANT",
    defaultTitle: "New Job Application Received",
    defaultBody: "A candidate submitted a new application for your job opening.",
    defaultCtaText: "Review Applicant",
    defaultCtaUrl: "/recruiter/applicants",
    isMandatory: false,
    emailEligible: true,
    dedupCooldownMinutes: 10,
  },
  RECRUITER_CANDIDATE_WITHDREW: {
    category: "APPLICATIONS",
    priority: "NORMAL",
    defaultTitle: "Candidate Withdrew Application",
    defaultBody: "A candidate has withdrawn their application.",
    defaultCtaText: "View Pipeline",
    defaultCtaUrl: "/recruiter/applicants",
    isMandatory: false,
    emailEligible: false,
    dedupCooldownMinutes: 0,
  },
  RECRUITER_CANDIDATE_UNLOCKED: {
    category: "APPLICATIONS",
    priority: "NORMAL",
    defaultTitle: "Candidate Profile Unlocked",
    defaultBody: "Candidate contact information and direct resume download are now available.",
    defaultCtaText: "View Profile",
    defaultCtaUrl: "/recruiter/candidates",
    isMandatory: false,
    emailEligible: false,
    dedupCooldownMinutes: 0,
  },
  RECRUITER_CONTACT_REQUEST_ACCEPTED: {
    category: "MESSAGES",
    priority: "IMPORTANT",
    defaultTitle: "Contact Consent Granted by Candidate",
    defaultBody: "A candidate accepted your contact request and shared direct contact info.",
    defaultCtaText: "View Contact Details",
    defaultCtaUrl: "/recruiter/candidates",
    isMandatory: false,
    emailEligible: true,
    dedupCooldownMinutes: 0,
  },
  RECRUITER_CONTACT_REQUEST_DECLINED: {
    category: "MESSAGES",
    priority: "NORMAL",
    defaultTitle: "Contact Request Declined",
    defaultBody: "Candidate preferred to communicate via platform chat.",
    defaultCtaText: "Open Messages",
    defaultCtaUrl: "/messages",
    isMandatory: false,
    emailEligible: false,
    dedupCooldownMinutes: 0,
  },
  RECRUITER_CANDIDATE_STAGE_MOVED: {
    category: "APPLICATIONS",
    priority: "INFORMATIONAL",
    defaultTitle: "Candidate Moved in Pipeline",
    defaultBody: "Candidate stage updated in recruitment pipeline.",
    defaultCtaText: "View Pipeline",
    defaultCtaUrl: "/recruiter/applicants",
    isMandatory: false,
    emailEligible: false,
    dedupCooldownMinutes: 0,
  },
  RECRUITER_SLA_WARNING: {
    category: "APPLICATIONS",
    priority: "IMPORTANT",
    defaultTitle: "⚠️ Hiring SLA Review Approaching",
    defaultBody: "Candidates in your pipeline are approaching the response SLA deadline.",
    defaultCtaText: "Review Pending Applicants",
    defaultCtaUrl: "/recruiter/applicants",
    isMandatory: false,
    emailEligible: true,
    dedupCooldownMinutes: 720,
  },
  RECRUITER_SLA_BREACHED: {
    category: "APPLICATIONS",
    priority: "CRITICAL",
    defaultTitle: "🚨 Response SLA Breached",
    defaultBody: "Candidates have waited past the company review target without an update.",
    defaultCtaText: "Update Candidates Now",
    defaultCtaUrl: "/recruiter/applicants",
    isMandatory: false,
    emailEligible: true,
    dedupCooldownMinutes: 1440,
  },
  RECRUITER_CANDIDATE_BACKLOG_ALERT: {
    category: "APPLICATIONS",
    priority: "IMPORTANT",
    defaultTitle: "Candidate Backlog Warning",
    defaultBody: "Multiple applicants require recruiter action to keep hiring velocity high.",
    defaultCtaText: "Manage Pipeline",
    defaultCtaUrl: "/recruiter/applicants",
    isMandatory: false,
    emailEligible: true,
    dedupCooldownMinutes: 1440,
  },

  // --- RECRUITER: MESSAGES & INTERVIEWS ---
  RECRUITER_MESSAGE_RECEIVED: {
    category: "MESSAGES",
    priority: "IMPORTANT",
    defaultTitle: "New Candidate Message",
    defaultBody: "A candidate sent a response in platform chat.",
    defaultCtaText: "Reply",
    defaultCtaUrl: "/messages",
    isMandatory: false,
    emailEligible: true,
    dedupCooldownMinutes: 5,
  },
  RECRUITER_CANDIDATE_REPLY: {
    category: "MESSAGES",
    priority: "IMPORTANT",
    defaultTitle: "Candidate Replied to Outreach",
    defaultBody: "A candidate responded to your inquiry.",
    defaultCtaText: "View Message",
    defaultCtaUrl: "/messages",
    isMandatory: false,
    emailEligible: true,
    dedupCooldownMinutes: 5,
  },
  RECRUITER_UNANSWERED_MESSAGE_REMINDER: {
    category: "MESSAGES",
    priority: "NORMAL",
    defaultTitle: "Unanswered Candidate Message",
    defaultBody: "An applicant is waiting for your reply.",
    defaultCtaText: "Reply in Chat",
    defaultCtaUrl: "/messages",
    isMandatory: false,
    emailEligible: true,
    dedupCooldownMinutes: 1440,
  },
  RECRUITER_INTERVIEW_SCHEDULED: {
    category: "INTERVIEWS",
    priority: "IMPORTANT",
    defaultTitle: "Interview Scheduled with Candidate",
    defaultBody: "Interview session details logged in candidate timeline.",
    defaultCtaText: "View Details",
    defaultCtaUrl: "/recruiter/applicants",
    isMandatory: false,
    emailEligible: true,
    dedupCooldownMinutes: 0,
  },
  RECRUITER_INTERVIEW_CONFIRMED: {
    category: "INTERVIEWS",
    priority: "IMPORTANT",
    defaultTitle: "Candidate Confirmed Interview",
    defaultBody: "The candidate confirmed their attendance for the scheduled interview round.",
    defaultCtaText: "View Schedule",
    defaultCtaUrl: "/recruiter/applicants",
    isMandatory: false,
    emailEligible: true,
    dedupCooldownMinutes: 0,
  },
  RECRUITER_INTERVIEW_RESCHEDULE_REQUESTED: {
    category: "INTERVIEWS",
    priority: "IMPORTANT",
    defaultTitle: "Candidate Requested Reschedule",
    defaultBody: "A candidate requested an alternate time slot for their interview.",
    defaultCtaText: "Reschedule Session",
    defaultCtaUrl: "/recruiter/applicants",
    isMandatory: false,
    emailEligible: true,
    dedupCooldownMinutes: 0,
  },
  RECRUITER_INTERVIEW_COMPLETED: {
    category: "INTERVIEWS",
    priority: "NORMAL",
    defaultTitle: "Interview Round Completed",
    defaultBody: "Please submit candidate scorecards and feedback.",
    defaultCtaText: "Submit Feedback",
    defaultCtaUrl: "/recruiter/applicants",
    isMandatory: false,
    emailEligible: false,
    dedupCooldownMinutes: 0,
  },
  RECRUITER_INTERVIEW_FEEDBACK_OVERDUE: {
    category: "INTERVIEWS",
    priority: "IMPORTANT",
    defaultTitle: "Interview Feedback Overdue",
    defaultBody: "Scorecard feedback is needed for an interview conducted recently.",
    defaultCtaText: "Submit Evaluation",
    defaultCtaUrl: "/recruiter/applicants",
    isMandatory: false,
    emailEligible: true,
    dedupCooldownMinutes: 720,
  },

  // --- RECRUITER: BILLING & QUOTAS ---
  RECRUITER_TRIAL_STARTED: {
    category: "BILLING",
    priority: "IMPORTANT",
    defaultTitle: "Recruiter Trial Activated",
    defaultBody: "Your 5 free candidate searches and 1 job posting are now ready to use.",
    defaultCtaText: "Search Candidates",
    defaultCtaUrl: "/recruiter/candidates",
    isMandatory: false,
    emailEligible: true,
    dedupCooldownMinutes: 1440,
  },
  RECRUITER_TRIAL_REMINDER: {
    category: "BILLING",
    priority: "NORMAL",
    defaultTitle: "Trial Usage Summary",
    defaultBody: "You have active trial candidate searches available in your recruiter workspace.",
    defaultCtaText: "Source Candidates",
    defaultCtaUrl: "/recruiter/candidates",
    isMandatory: false,
    emailEligible: true,
    dedupCooldownMinutes: 1440,
  },
  RECRUITER_TRIAL_ENDED: {
    category: "BILLING",
    priority: "IMPORTANT",
    defaultTitle: "Recruiter Trial Completed",
    defaultBody: "You have used your 5 free searches. Upgrade to a paid plan for unlimited sourcing and verified resume downloads.",
    defaultCtaText: "View Subscription Plans",
    defaultCtaUrl: "/recruiter/billing",
    isMandatory: false,
    emailEligible: true,
    dedupCooldownMinutes: 1440,
  },
  RECRUITER_SUBSCRIPTION_ACTIVATED: {
    category: "BILLING",
    priority: "CRITICAL",
    defaultTitle: "Subscription Activated",
    defaultBody: "Thank you for upgrading! Your recruiter subscription tier is now active.",
    defaultCtaText: "Manage Subscription",
    defaultCtaUrl: "/recruiter/billing",
    isMandatory: true,
    emailEligible: true,
    dedupCooldownMinutes: 0,
  },
  RECRUITER_SUBSCRIPTION_UPGRADED: {
    category: "BILLING",
    priority: "CRITICAL",
    defaultTitle: "Subscription Tier Upgraded",
    defaultBody: "Your account has been upgraded with higher daily candidate unlock and resume limits.",
    defaultCtaText: "View Entitlements",
    defaultCtaUrl: "/recruiter/billing",
    isMandatory: true,
    emailEligible: true,
    dedupCooldownMinutes: 0,
  },
  RECRUITER_SUBSCRIPTION_DOWNGRADED: {
    category: "BILLING",
    priority: "IMPORTANT",
    defaultTitle: "Subscription Tier Adjusted",
    defaultBody: "Your subscription tier change has been processed.",
    defaultCtaText: "Manage Billing",
    defaultCtaUrl: "/recruiter/billing",
    isMandatory: true,
    emailEligible: true,
    dedupCooldownMinutes: 0,
  },
  RECRUITER_SUBSCRIPTION_CANCELLED: {
    category: "BILLING",
    priority: "CRITICAL",
    defaultTitle: "Subscription Cancelled",
    defaultBody: "Your recruiter subscription has been cancelled and will expire at the end of the billing cycle.",
    defaultCtaText: "Review Plan",
    defaultCtaUrl: "/recruiter/billing",
    isMandatory: true,
    emailEligible: true,
    dedupCooldownMinutes: 0,
  },
  RECRUITER_PAYMENT_SUCCESSFUL: {
    category: "BILLING",
    priority: "IMPORTANT",
    defaultTitle: "Payment Receipt",
    defaultBody: "Your subscription payment was processed successfully. Receipt is available.",
    defaultCtaText: "View Invoices",
    defaultCtaUrl: "/recruiter/billing",
    isMandatory: true,
    emailEligible: true,
    dedupCooldownMinutes: 0,
  },
  RECRUITER_PAYMENT_FAILED: {
    category: "BILLING",
    priority: "CRITICAL",
    defaultTitle: "Payment Failed: Action Required",
    defaultBody: "We were unable to process your recurring subscription payment. Please update payment method to avoid service interruption.",
    defaultCtaText: "Update Billing Info",
    defaultCtaUrl: "/recruiter/billing",
    isMandatory: true,
    emailEligible: true,
    dedupCooldownMinutes: 720,
  },
  RECRUITER_QUOTA_APPROACHING_LIMIT: {
    category: "BILLING",
    priority: "IMPORTANT",
    defaultTitle: "Daily Quota Limit Approaching",
    defaultBody: "You have used 80% of your daily candidate unlock or search quota.",
    defaultCtaText: "Upgrade Quota",
    defaultCtaUrl: "/recruiter/billing",
    isMandatory: false,
    emailEligible: true,
    dedupCooldownMinutes: 720,
  },
  RECRUITER_QUOTA_EXHAUSTED: {
    category: "BILLING",
    priority: "IMPORTANT",
    defaultTitle: "Daily Quota Reached",
    defaultBody: "You have reached your plan's daily candidate unlock limit. Resets at midnight.",
    defaultCtaText: "Upgrade Plan",
    defaultCtaUrl: "/recruiter/billing",
    isMandatory: false,
    emailEligible: true,
    dedupCooldownMinutes: 720,
  },

  // --- TALENT INTELLIGENCE ---
  TALENT_DEMAND_ALERT: {
    category: "TALENT_INTELLIGENCE",
    priority: "NORMAL",
    defaultTitle: "🔥 Talent Demand Detected",
    defaultBody: "Discoverable candidates match your recent technical role search.",
    defaultCtaText: "Explore Matching Talent",
    defaultCtaUrl: "/recruiter/candidates",
    isMandatory: false,
    emailEligible: true,
    dedupCooldownMinutes: 1440,
  },
  JOB_TO_TALENT_MATCH_ALERT: {
    category: "TALENT_INTELLIGENCE",
    priority: "IMPORTANT",
    defaultTitle: "🎯 Your New Job Matches Available Talent",
    defaultBody: "Discoverable candidates in PostgreSQL match your newly published position requirements.",
    defaultCtaText: "Review Matching Candidates",
    defaultCtaUrl: "/recruiter/candidates",
    isMandatory: false,
    emailEligible: true,
    dedupCooldownMinutes: 720,
  },
  NEW_MATCHING_TALENT_ALERT: {
    category: "TALENT_INTELLIGENCE",
    priority: "NORMAL",
    defaultTitle: "🧠 New Matching Talent Available",
    defaultBody: "Newly registered discoverable candidates match your open roles.",
    defaultCtaText: "View New Talent",
    defaultCtaUrl: "/recruiter/candidates",
    isMandatory: false,
    emailEligible: true,
    dedupCooldownMinutes: 720,
  },
  SEARCH_INTENT_TALENT_ALERT: {
    category: "TALENT_INTELLIGENCE",
    priority: "NORMAL",
    defaultTitle: "Candidate Matches for Your Search Intent",
    defaultBody: "New candidates match your frequently searched skills.",
    defaultCtaText: "View Matches",
    defaultCtaUrl: "/recruiter/candidates",
    isMandatory: false,
    emailEligible: false,
    dedupCooldownMinutes: 1440,
  },
  TALENT_SUPPLY_TREND_ALERT: {
    category: "TALENT_INTELLIGENCE",
    priority: "INFORMATIONAL",
    defaultTitle: "📈 Talent Supply Shift Alert",
    defaultBody: "Significant market candidate supply changes detected in key engineering categories.",
    defaultCtaText: "Open Talent Radar",
    defaultCtaUrl: "/recruiter",
    isMandatory: false,
    emailEligible: false,
    dedupCooldownMinutes: 4320,
  },
  RECRUITER_WEEKLY_INTELLIGENCE_DIGEST: {
    category: "TALENT_INTELLIGENCE",
    priority: "NORMAL",
    defaultTitle: "NextHire Weekly Talent Intelligence Digest",
    defaultBody: "Your weekly summary of matching talent, supply shifts, and applicant activity.",
    defaultCtaText: "Open Talent Intelligence",
    defaultCtaUrl: "/recruiter",
    isMandatory: false,
    emailEligible: true,
    dedupCooldownMinutes: 10080, // 7 days
  },

  // --- OWNER / PLATFORM ADMIN ---
  ADMIN_PLATFORM_HEALTH_ALERT: {
    category: "SYSTEM",
    priority: "CRITICAL",
    defaultTitle: "Platform Operational Health Alert",
    defaultBody: "A critical system event requires administrative attention.",
    defaultCtaText: "Open Admin Console",
    defaultCtaUrl: "/admin",
    isMandatory: true,
    emailEligible: true,
    dedupCooldownMinutes: 60,
  },
  ADMIN_API_FAILURE_SPIKE: {
    category: "SYSTEM",
    priority: "CRITICAL",
    defaultTitle: "API Failure Spike Detected",
    defaultBody: "Elevated error rates detected on platform API endpoints.",
    defaultCtaText: "View Audit Trail",
    defaultCtaUrl: "/admin",
    isMandatory: true,
    emailEligible: true,
    dedupCooldownMinutes: 30,
  },
  ADMIN_EMAIL_PROVIDER_FAILURE: {
    category: "SYSTEM",
    priority: "CRITICAL",
    defaultTitle: "Email Provider Dispatch Failure",
    defaultBody: "Resend email provider dispatch returned elevated failure status.",
    defaultCtaText: "Check Logs",
    defaultCtaUrl: "/admin",
    isMandatory: true,
    emailEligible: false,
    dedupCooldownMinutes: 60,
  },
  ADMIN_CRON_FAILURE: {
    category: "SYSTEM",
    priority: "IMPORTANT",
    defaultTitle: "Scheduled Worker Failure",
    defaultBody: "A background digest or SLA scanning worker failed execution.",
    defaultCtaText: "View System Logs",
    defaultCtaUrl: "/admin",
    isMandatory: true,
    emailEligible: true,
    dedupCooldownMinutes: 60,
  },
  ADMIN_SECURITY_INCIDENT: {
    category: "SECURITY",
    priority: "CRITICAL",
    defaultTitle: "Security Incident Alert",
    defaultBody: "Suspicious activity pattern or brute-force signature detected.",
    defaultCtaText: "Review Security Logs",
    defaultCtaUrl: "/admin",
    isMandatory: true,
    emailEligible: true,
    dedupCooldownMinutes: 15,
  },
  ADMIN_SUSPICIOUS_REGISTRATION: {
    category: "SECURITY",
    priority: "IMPORTANT",
    defaultTitle: "Suspicious User Registration",
    defaultBody: "A registration triggered automated fraud or spam heuristics.",
    defaultCtaText: "Review User",
    defaultCtaUrl: "/admin/users",
    isMandatory: true,
    emailEligible: false,
    dedupCooldownMinutes: 30,
  },
  ADMIN_COMPANY_VERIFICATION_REQUESTED: {
    category: "SECURITY",
    priority: "IMPORTANT",
    defaultTitle: "New Company Verification Pending",
    defaultBody: "An employer organization submitted documents for verification review.",
    defaultCtaText: "Review Company",
    defaultCtaUrl: "/admin/companies",
    isMandatory: false,
    emailEligible: true,
    dedupCooldownMinutes: 60,
  },
  ADMIN_RECRUITER_VERIFICATION_REQUESTED: {
    category: "SECURITY",
    priority: "IMPORTANT",
    defaultTitle: "New Recruiter Verification Pending",
    defaultBody: "A recruiter submitted credentials for platform approval.",
    defaultCtaText: "Review Recruiter",
    defaultCtaUrl: "/admin/users",
    isMandatory: false,
    emailEligible: true,
    dedupCooldownMinutes: 60,
  },
  ADMIN_JOB_REPORTED: {
    category: "SYSTEM",
    priority: "CRITICAL",
    defaultTitle: "Job Posting Flagged / Reported",
    defaultBody: "A job listing has been flagged by users for moderation review.",
    defaultCtaText: "Moderate Job",
    defaultCtaUrl: "/admin",
    isMandatory: true,
    emailEligible: true,
    dedupCooldownMinutes: 0,
  },
  ADMIN_USER_REPORTED: {
    category: "SYSTEM",
    priority: "CRITICAL",
    defaultTitle: "User Profile Reported",
    defaultBody: "A user profile was reported for safety or policy review.",
    defaultCtaText: "Review Profile",
    defaultCtaUrl: "/admin/users",
    isMandatory: true,
    emailEligible: true,
    dedupCooldownMinutes: 0,
  },
  ADMIN_REVENUE_MILESTONE: {
    category: "BILLING",
    priority: "INFORMATIONAL",
    defaultTitle: "Platform MRR Milestone Reached",
    defaultBody: "Subscription revenue has crossed an established platform milestone.",
    defaultCtaText: "View Subscriptions",
    defaultCtaUrl: "/admin/subscriptions",
    isMandatory: false,
    emailEligible: true,
    dedupCooldownMinutes: 1440,
  },
  ADMIN_PAYMENT_FAILURE_SPIKE: {
    category: "BILLING",
    priority: "CRITICAL",
    defaultTitle: "Payment Failure Spike",
    defaultBody: "Multiple consecutive subscription payment failures detected.",
    defaultCtaText: "Inspect Billing Logs",
    defaultCtaUrl: "/admin/subscriptions",
    isMandatory: true,
    emailEligible: true,
    dedupCooldownMinutes: 120,
  },
  ADMIN_WEEKLY_PLATFORM_DIGEST: {
    category: "SYSTEM",
    priority: "NORMAL",
    defaultTitle: "NextHire Weekly Platform Executive Summary",
    defaultBody: "Executive overview of active users, jobs, applications, revenue, and system health.",
    defaultCtaText: "Open Admin Overview",
    defaultCtaUrl: "/admin",
    isMandatory: false,
    emailEligible: true,
    dedupCooldownMinutes: 10080,
  },

  // --- SYSTEM GENERAL ---
  SYSTEM_GENERAL_ALERT: {
    category: "SYSTEM",
    priority: "NORMAL",
    defaultTitle: "NextHire System Notification",
    defaultBody: "Important platform operational notification.",
    defaultCtaText: "View Details",
    defaultCtaUrl: "/dashboard",
    isMandatory: false,
    emailEligible: false,
    dedupCooldownMinutes: 60,
  },
  SYSTEM_MAINTENANCE_NOTICE: {
    category: "SYSTEM",
    priority: "IMPORTANT",
    defaultTitle: "Scheduled Maintenance Notice",
    defaultBody: "NextHire will undergo scheduled infrastructure optimization.",
    defaultCtaText: "Read Details",
    defaultCtaUrl: "/dashboard",
    isMandatory: true,
    emailEligible: true,
    dedupCooldownMinutes: 1440,
  },
};
