import { UserRole } from "@prisma/client";

export type NotificationCategory =
  | "APPLICATIONS"
  | "MESSAGES"
  | "INTERVIEWS"
  | "JOBS"
  | "TALENT_INTELLIGENCE"
  | "BILLING"
  | "SECURITY"
  | "SYSTEM";

export type NotificationPriority =
  | "CRITICAL"
  | "IMPORTANT"
  | "NORMAL"
  | "INFORMATIONAL";

export type EmailDeliveryStatus =
  | "NOT_QUEUED"
  | "QUEUED"
  | "SENDING"
  | "SENT"
  | "DELIVERED"
  | "FAILED"
  | "RETRYING"
  | "SKIPPED_PREFERENCE";

export type DigestFrequency = "INSTANT" | "DAILY" | "WEEKLY" | "NONE";

export type AppEventType =
  // --- JOB SEEKER: ACCOUNT & SECURITY ---
  | "SEEKER_ACCOUNT_CREATED"
  | "SEEKER_WELCOME"
  | "SEEKER_EMAIL_VERIFICATION_SENT"
  | "SEEKER_VERIFICATION_COMPLETED"
  | "SEEKER_PASSWORD_CHANGED"
  | "SEEKER_PASSWORD_RESET_REQUESTED"
  | "SEEKER_SUSPICIOUS_LOGIN"
  | "SEEKER_ACCOUNT_RESTRICTED"
  | "SEEKER_ACCOUNT_RESTORED"

  // --- JOB SEEKER: PROFILE & ATS RESUME ---
  | "SEEKER_PROFILE_INCOMPLETE_REMINDER"
  | "SEEKER_PROFILE_COMPLETED"
  | "SEEKER_PROFILE_VIEWED"
  | "SEEKER_RECRUITER_SAVED_PROFILE"
  | "SEEKER_RESUME_UPLOADED"
  | "SEEKER_RESUME_PARSED"
  | "SEEKER_RESUME_PARSE_FAILED"
  | "SEEKER_PROFILE_SYNCED"
  | "SEEKER_ATS_SCORE_GENERATED"
  | "SEEKER_ATS_SCORE_IMPROVED"
  | "SEEKER_PROFILE_IMPROVEMENT_TIP"

  // --- JOB SEEKER: JOB DISCOVERY ---
  | "SEEKER_JOB_MATCH_DISCOVERED"
  | "SEEKER_HIGH_SKILL_MATCH"
  | "SEEKER_SAVED_JOB_CLOSING_SOON"
  | "SEEKER_SAVED_JOB_EXPIRED"
  | "SEEKER_RECOMMENDED_OPPORTUNITY"

  // --- JOB SEEKER: APPLICATIONS & MILESTONES ---
  | "SEEKER_APPLICATION_SUBMITTED"
  | "SEEKER_APPLICATION_RECEIVED"
  | "SEEKER_APPLICATION_VIEWED"
  | "SEEKER_APPLICATION_SHORTLISTED"
  | "SEEKER_APPLICATION_STAGE_CHANGED"
  | "SEEKER_APPLICATION_REJECTED"
  | "SEEKER_APPLICATION_WITHDRAWN"
  | "SEEKER_APPLICATION_MILESTONE_REACHED"

  // --- JOB SEEKER: MESSAGES & INTERVIEWS ---
  | "SEEKER_MESSAGE_RECEIVED"
  | "SEEKER_RECRUITER_INQUIRY"
  | "SEEKER_UNANSWERED_MESSAGE_REMINDER"
  | "SEEKER_INTERVIEW_INVITATION"
  | "SEEKER_INTERVIEW_SCHEDULED"
  | "SEEKER_INTERVIEW_CONFIRMED"
  | "SEEKER_INTERVIEW_RESCHEDULED"
  | "SEEKER_INTERVIEW_REMINDER_24H"
  | "SEEKER_INTERVIEW_REMINDER_1H"
  | "SEEKER_INTERVIEW_COMPLETED"
  | "SEEKER_INTERVIEW_FEEDBACK_REQUESTED"

  // --- JOB SEEKER: OFFERS ---
  | "SEEKER_OFFER_RECEIVED"
  | "SEEKER_OFFER_UPDATED"
  | "SEEKER_OFFER_DEADLINE_APPROACHING"
  | "SEEKER_OFFER_ACCEPTED"
  | "SEEKER_OFFER_DECLINED"

  // --- RECRUITER: ACCOUNT & VERIFICATION ---
  | "RECRUITER_REGISTERED"
  | "RECRUITER_WELCOME"
  | "RECRUITER_VERIFICATION_REQUESTED"
  | "RECRUITER_VERIFICATION_APPROVED"
  | "RECRUITER_VERIFICATION_REJECTED"
  | "RECRUITER_SECURITY_ALERT"

  // --- RECRUITER: COMPANY & BRANDING ---
  | "RECRUITER_COMPANY_CREATED"
  | "RECRUITER_COMPANY_UPDATED"
  | "RECRUITER_COMPANY_VERIFICATION_SUBMITTED"
  | "RECRUITER_COMPANY_VERIFIED"
  | "RECRUITER_COMPANY_VERIFICATION_REJECTED"

  // --- RECRUITER: JOB LIFECYCLE ---
  | "RECRUITER_JOB_DRAFT_SAVED"
  | "RECRUITER_JOB_PUBLISHED"
  | "RECRUITER_JOB_PAUSED"
  | "RECRUITER_JOB_RESUMED"
  | "RECRUITER_JOB_EXPIRING"
  | "RECRUITER_JOB_EXPIRED"
  | "RECRUITER_JOB_APPLICATION_MILESTONE"

  // --- RECRUITER: CANDIDATE ACTIVITY & ATS ---
  | "RECRUITER_NEW_APPLICATION"
  | "RECRUITER_CANDIDATE_WITHDREW"
  | "RECRUITER_CANDIDATE_UNLOCKED"
  | "RECRUITER_CONTACT_REQUEST_ACCEPTED"
  | "RECRUITER_CONTACT_REQUEST_DECLINED"
  | "RECRUITER_CANDIDATE_STAGE_MOVED"
  | "RECRUITER_SLA_WARNING"
  | "RECRUITER_SLA_BREACHED"
  | "RECRUITER_CANDIDATE_BACKLOG_ALERT"

  // --- RECRUITER: MESSAGES & INTERVIEWS ---
  | "RECRUITER_MESSAGE_RECEIVED"
  | "RECRUITER_CANDIDATE_REPLY"
  | "RECRUITER_UNANSWERED_MESSAGE_REMINDER"
  | "RECRUITER_INTERVIEW_SCHEDULED"
  | "RECRUITER_INTERVIEW_CONFIRMED"
  | "RECRUITER_INTERVIEW_RESCHEDULE_REQUESTED"
  | "RECRUITER_INTERVIEW_COMPLETED"
  | "RECRUITER_INTERVIEW_FEEDBACK_OVERDUE"

  // --- RECRUITER: BILLING & QUOTAS ---
  | "RECRUITER_TRIAL_STARTED"
  | "RECRUITER_TRIAL_REMINDER"
  | "RECRUITER_TRIAL_ENDED"
  | "RECRUITER_SUBSCRIPTION_ACTIVATED"
  | "RECRUITER_SUBSCRIPTION_UPGRADED"
  | "RECRUITER_SUBSCRIPTION_DOWNGRADED"
  | "RECRUITER_SUBSCRIPTION_CANCELLED"
  | "RECRUITER_PAYMENT_SUCCESSFUL"
  | "RECRUITER_PAYMENT_FAILED"
  | "RECRUITER_QUOTA_APPROACHING_LIMIT"
  | "RECRUITER_QUOTA_EXHAUSTED"

  // --- TALENT INTELLIGENCE ---
  | "TALENT_DEMAND_ALERT"
  | "JOB_TO_TALENT_MATCH_ALERT"
  | "NEW_MATCHING_TALENT_ALERT"
  | "SEARCH_INTENT_TALENT_ALERT"
  | "TALENT_SUPPLY_TREND_ALERT"
  | "RECRUITER_WEEKLY_INTELLIGENCE_DIGEST"

  // --- OWNER / PLATFORM ADMIN ---
  | "ADMIN_PLATFORM_HEALTH_ALERT"
  | "ADMIN_API_FAILURE_SPIKE"
  | "ADMIN_EMAIL_PROVIDER_FAILURE"
  | "ADMIN_CRON_FAILURE"
  | "ADMIN_SECURITY_INCIDENT"
  | "ADMIN_SUSPICIOUS_REGISTRATION"
  | "ADMIN_COMPANY_VERIFICATION_REQUESTED"
  | "ADMIN_RECRUITER_VERIFICATION_REQUESTED"
  | "ADMIN_JOB_REPORTED"
  | "ADMIN_USER_REPORTED"
  | "ADMIN_REVENUE_MILESTONE"
  | "ADMIN_PAYMENT_FAILURE_SPIKE"
  | "ADMIN_WEEKLY_PLATFORM_DIGEST"

  // --- EVIDENCE-BASED SKILLS ASSESSMENTS ---
  | "ASSESSMENT_CREATED"
  | "ASSESSMENT_SENT"
  | "ASSESSMENT_STARTED"
  | "ASSESSMENT_SUBMITTED"
  | "ASSESSMENT_DEADLINE_APPROACHING"
  | "ASSESSMENT_COMPLETED"
  | "ASSESSMENT_REVIEW_REQUIRED"

  // --- AI RECRUITER OUTREACH & ENGAGEMENT ---
  | "OUTREACH_CAMPAIGN_CREATED"
  | "OUTREACH_APPROVAL_REQUIRED"
  | "OUTREACH_SENT"
  | "OUTREACH_DELIVERED"
  | "OUTREACH_FAILED"
  | "CANDIDATE_REPLIED"
  | "CANDIDATE_POSITIVE_RESPONSE"
  | "OUTREACH_FOLLOWUP_DUE"
  | "CANDIDATE_OPTED_OUT"

  // --- INTERVIEW INTELLIGENCE & DECISIONS ---
  | "INTERVIEW_PLAN_GENERATED"
  | "INTERVIEW_SCORECARD_REQUIRED"
  | "INTERVIEW_FEEDBACK_SUBMITTED"
  | "INTERVIEW_FEEDBACK_OVERDUE"
  | "INTERVIEW_SUMMARY_READY"
  | "INTERVIEW_DECISION_REQUIRED"
  | "INTERVIEW_DECISION_CONFIRMED"
  | "INTERVIEW_EVIDENCE_CONFLICT"

  // --- HIRING FUNNEL INTELLIGENCE & STRATEGY (PHASE 11) ---
  | "RECRUITER_JOB_FUNNEL_AT_RISK"
  | "RECRUITER_JOB_FUNNEL_CRITICAL"
  | "RECRUITER_CANDIDATE_STALLED"
  | "RECRUITER_REVIEW_BACKLOG"
  | "RECRUITER_SCORECARD_BACKLOG"
  | "RECRUITER_HIRING_TARGET_AT_RISK"
  | "RECRUITER_ACTION_PLAN_READY"

  // --- MARKET & TALENT SUPPLY INTELLIGENCE (PHASE 12) ---
  | "RECRUITER_TALENT_SUPPLY_LOW"
  | "RECRUITER_SKILL_SCARCITY_DETECTED"
  | "RECRUITER_SUPPLY_CONSTRAINT_DETECTED"
  | "RECRUITER_MARKET_TREND_CHANGED"
  | "RECRUITER_SOURCING_STRATEGY_RECOMMENDED"

  // --- RECRUITER GROWTH, TEAM COLLABORATION & HIRING OPERATIONS (PHASE 13) ---
  | "RECRUITER_CANDIDATE_ASSIGNED"
  | "RECRUITER_CANDIDATE_REASSIGNED"
  | "RECRUITER_JOB_ASSIGNED"
  | "RECRUITER_HANDOFF_RECEIVED"
  | "RECRUITER_HANDOFF_OVERDUE"
  | "RECRUITER_TASK_ASSIGNED"
  | "RECRUITER_TASK_OVERDUE"
  | "RECRUITER_MENTIONED"
  | "RECRUITER_DUPLICATE_WORK_DETECTED"
  | "RECRUITER_TEAM_CAPACITY_ALERT"

  // --- SYSTEM GENERAL ---
  | "SYSTEM_GENERAL_ALERT"
  | "SYSTEM_MAINTENANCE_NOTICE";

export interface EmitEventParams {
  type: AppEventType;
  recipientId: string;
  actorId?: string;
  actorName?: string;
  recipientEmail?: string;
  recipientRole?: UserRole;
  companyId?: string;
  entityType?: string;
  entityId?: string;
  title?: string;
  body?: string;
  category?: NotificationCategory;
  priority?: NotificationPriority;
  ctaText?: string;
  ctaUrl?: string;
  metadata?: Record<string, any>;
  dedupKey?: string;
  sendEmail?: boolean;
  emailSubject?: string;
  emailHtml?: string;
  customCooldownMinutes?: number;
}

export interface EmitEventResult {
  success: boolean;
  notificationId?: string;
  emailStatus: EmailDeliveryStatus;
  skippedReason?: string;
  error?: string;
}

export interface EventMetadataDefinition {
  category: NotificationCategory;
  priority: NotificationPriority;
  defaultTitle: string;
  defaultBody: string;
  defaultCtaText?: string;
  defaultCtaUrl?: string;
  isMandatory: boolean; // Cannot be opted out (Security, Suspensions, Critical Billing)
  emailEligible: boolean;
  dedupCooldownMinutes: number; // 0 = no cooldown, > 0 = cooldown window
}
